### ISSUE TITLE
File-error: Not found

### ISSUE THREAD

**Issue by artelse** [slotThe/vc-use-package#3] opened 2022-12-23 22:47 UTC
This could be my config, but am unsure what the problem is.
I try to fetch following package:
`(use-package expenses
  :vc (:fetcher "github" :repo "md-arif-shaikh/expenses")`

And get this error below. Before changing to `package-vc` I used `straight` with `use-package` just fine. Any ideas?

```
Debugger entered--Lisp error: (file-error "https://melpa.org/packages/elpa-packages.eld" "Not found")
  signal(file-error
         ("https://melpa.org/packages/elpa-packages.eld" "Not found"))
  package--with-response-buffer-1("https://melpa.org/packages/" #f(compiled-function () #<bytecode -0x15ea84ea0ecdb6ba>) :file "elpa-packages.eld" :async nil :error-function #f(compiled-function () #<bytecode -0x3d0ec9bee8a587c>) :noerror nil)
  package--download-one-archive(("melpa" . "https://melpa.org/packages/") "elpa-packages.eld" nil)
  package-vc--download-and-read-archives()
  package-vc--archives-initialize()
  package-vc-install("https://github.com/md-arif-shaikh/expenses" expenses nil nil)
  vc-use-package--install(:fetcher "https://github.com/" :repo "md-arif-shaikh/expenses" :name expenses)
  apply(vc-use-package--install (:fetcher "https://github.com/" :repo "md-arif-shaikh/expenses" :name expenses))
  (if (package-installed-p 'expenses) nil (apply #'vc-use-package--install '(:fetcher "https://github.com/" :repo "md-arif-shaikh/expenses" :name expenses)))
 ```

**Comment by alternateved** [comment] 2022-12-24 10:00
I had the same errors by evaluating `(package-vc-install "someURL")`. Those errors were gone for me after another evaluation and they did not happen when bootstrapping new configuration. I think the issue is with `package-vc-install` internals, but I did not dig deep enough (since the error was gone next time I used it), nevertheless I think this should be reported upstream.

**Comment by slotThe** [comment] 2022-12-24 10:34
Yeah I think this is unrelated to the package, and more to how `package-vc.el` works.   Seems like its trying to download some data base from MELPA, but the URL doesn't exist.  Evaluating 

``` emacs-lisp
(use-package expenses
  :vc (:fetcher "github" :repo "md-arif-shaikh/expenses"))
```

correctly install the package for me.

**Comment by slotThe** [comment] 2022-12-31 18:16
I'll close this for now, as it seems unrelated to the package.  Feel free to chime in again if something still does not work!

**Closed as completed by slotThe** 2022-12-31 18:16 UTC
